
language: node_js
node_js: '10.16.3'
branches:
  only:
  - master
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn purge
deploy:
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  target_branch: master
  verbose: true
  on:
    branch: master
