
language: node_js
node_js: '8'
branches:
  only:
  - master
  - /^greenkeeper/.*$/
  - /^renovate/.*$/
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:


  - yarn purge
  
 
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  
  verbose: true
  on:
    branch: master
