name: Auto comment

on:
  pull_request:
    branches:
    - master
jobs:
  auto_comment_on_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Add new comment reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          reaction-type: eyes
          body: |
            @${{ github.actor }}, thank you for raising a pull request.
            
            Please make sure you have followed @mazipan, and please push ⭐ button in this repository.
            I might will add a label `invalid` and close your PR if doesn't see your account give the star to this repo.
